### ISSUE TITLE
How to recursively process all .lua files in a directory?

### ISSUE THREAD

**Issue by xiangnanscu** [stevedonovan/lglob#6]
Hello `./lglob  ~/ngx/lualib/mvc` will get `luac: cannot read /root/ngx/lualib/mvc: Is a directory`.  How to  recursively process all .lua files in a directory?

**Comment by stevedonovan** [comment]
Does `./lglob ~/ngx/lualib/mvc/*` work for you? The star lets the shell do
the file expansion for you - but it won't be recursive, just into that one
directory. Let me think about this.

**Comment by xiangnanscu** [comment]
Worked but not recursively. Also, if there's only directories in mvc, lglob will show something like:
luac: cannot read /root/ngx/lualib/mvc/mvc: Is a directory
luac: cannot read /root/ngx/lualib/mvc/resty: Is a directory

**Comment by stevedonovan** [comment]
Right - I expected that. But I note there's an option to use the Unix
`find` command:

    ~/ngx/lualib/mvc$ lglob .

That is, if you're in the directory then '.' will follow all the *.lua
files.

**Comment by xiangnanscu** [comment]
Works. Thanks.
